//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Code4YeouidoWebService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Code4YeouidoEntities : DbContext
    {
        public Code4YeouidoEntities()
            : base("name=Code4YeouidoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BillChoice> BillChoice { get; set; }
        public virtual DbSet<BillList> BillList { get; set; }
        public virtual DbSet<MailList> MailList { get; set; }
        public virtual DbSet<MP> MP { get; set; }
        public virtual DbSet<DistrictInfo> DistrictInfo { get; set; }
    
        public virtual ObjectResult<Nullable<double>> GetAttendancePercentTop(string party, string name)
        {
            var partyParameter = party != null ?
                new ObjectParameter("Party", party) :
                new ObjectParameter("Party", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("GetAttendancePercentTop", partyParameter, nameParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> GetAttendanceRate(string party, string name)
        {
            var partyParameter = party != null ?
                new ObjectParameter("Party", party) :
                new ObjectParameter("Party", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("GetAttendanceRate", partyParameter, nameParameter);
        }
    
        public virtual ObjectResult<GetBillList_Result> GetBillList(string party, string name)
        {
            var partyParameter = party != null ?
                new ObjectParameter("Party", party) :
                new ObjectParameter("Party", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBillList_Result>("GetBillList", partyParameter, nameParameter);
        }
    }
}
