//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Code4YeouidoWebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MP
    {
        public int MPId { get; set; }
        public string NameKr { get; set; }
        public string NameEn { get; set; }
        public System.DateTime Birth { get; set; }
        public string Party { get; set; }
        public string District { get; set; }
        public string Committee { get; set; }
        public string WhenElected { get; set; }
        public string OffPhone { get; set; }
        public string Homepage { get; set; }
        public string Email { get; set; }
        public string Aides { get; set; }
        public string PrSecrs { get; set; }
        public string ScSecrs { get; set; }
        public string Hobby { get; set; }
        public string Experience { get; set; }
        public string Photo { get; set; }
        public string Url { get; set; }
        public string DistrictCompare { get; set; }
    }
}
